version: '3.1'
services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 8888:80
  #   depends_on: 
  #     - node
  node:
    build: ./app
    env_file: 
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3310:3306"
    env_file:
      - "./.env"
